@api = http://localhost:5000
@accessToken = 
@courseId = 
@moduleId = 

# ================== IDENTITY ================== #

### POST sign-up
POST {{api}}/identity/sign-up
Content-Type: application/json

{
  "email": "admin-user1@mailinator.com",
  "password": "secret",
  "role": "admin"
}

### POST sign-in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "admin-user1@mailinator.com",
  "password": "secret"
}

### GET me
GET {{api}}/identity/me
Authorization: Bearer {{accessToken}}


# ================== COURSES ================== #

### GET courses
GET {{api}}/courses
Content-Type: application/json

### GET specific course
GET {{api}}/courses/{{courseId}}
Content-Type: application/json

### GET modules from course
GET {{api}}/courses/{{courseId}}/modules
Content-Type: application/json

### GET specific module from course
GET {{api}}/courses/{{courseId}}/modules/{{moduleId}}
Content-Type: application/json

### POST course
POST {{api}}/courses
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "Title": "Awesome Course",
  "Description": "Awesome Course Description",
  "Tags": ["course", "tags"]
}

### POST course module
POST {{api}}/courses/{{courseId}}/modules
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "moduleName": "First Module",
  "description": "Module description",
  "moduleOrder": 1
}